---
title: 'Suggested Reading and References'
teaching: 10
exercises: 0
editor_options: 
  markdown: 
    wrap: 72
---

::: questions
-   How can I learn more?
:::

::: objectives
-   Become familiar with useful references.
:::

## Background on the Science

1. [The ecologist’s field guide to sequence‐based identification of biodiversity](https://doi.org/10.1111/2041-210X.12574) (Creer et al, 2016)
1. [Past, present, and future perspectives of environmental DNA (eDNA) metabarcoding: A systematic review in methods, monitoring, and applications of global eDNA](https://doi.org/10.1016/j.gecco.2019.e00547) (Ruppert et al., 2019)
1. [Critical considerations for communicating environmental DNA science](https://doi.org/10.1002/edn3.472) (Stein et al., 2024)
1. [How, What, and Where You Sample Environmental DNA Affects Diversity Estimates and Species Detection](https://doi.org/10.1002/edn3.70042) (Kirtane et al., 2024)
1. [A Guide to Environmental DNA Extractions for Non‐Molecular Trained Biologists, Ecologists, and Conservation Scientists](https://doi.org/10.1002/edn3.70002) (Rieder et al., 2024)

## Data Management and Standards

1. [Publishing DNA‐derived data through biodiversity data platforms.](https://doi.org/10.35035/DOC-VF1A-NR22) (Finstad et al., 2023)
1. [A Practical Approach to Using the Genomic Standards Consortium MIxS Reporting Standard for Comparative Genomics and Metagenomics](https://doi.org/10.1007/978-1-0716-3838-5_20) (Eloe‐Fadrosh et al., 2024)
1. [The MIEM guidelines: Minimum information for reporting of environmental metabarcoding data](https://doi.org/10.3897/mbmg.8.128689). (Klymus et al. 2024)
1. [Best practices for genetic and genomic data archiving](https://doi.org/10.1038/s41559-024-02423-7) (Leigh et al., 2024)
1. [Centering accessibility, increasing capacity, and fostering innovation in the development of international eDNA standards](https://doi.org/10.3897/mbmg.8.126058) (Hirsch et al., 2024)

## Policy

1. [National Aquatic Environmental DNA Strategy](https://www.whitehouse.gov/wp-content/uploads/2024/06/NSTC_National-Aquatic-eDNA-Strategy.pdf) (eDNA Task Team, 2024)

## Standards Reference Material

1. [Publishing DNA‐derived data through biodiversity data platforms.](https://doi.org/10.35035/DOC-VF1A-NR22) (Finstad wt al., 2023)

#### Darwin Core
1. Quick Reference Guide (term search): <https://dwc.tdwg.org/terms/>
1. DNA Derived Data Extension: [https://rs.gbif.org/extension/gbif/1.0/dna_derived_data\_2022‐02‐23.xml](https://rs.gbif.org/extension/gbif/1.0/dna_derived_data_2022-02-23.xml)

#### MIxS
1. Intro: [https://www.gensc.org/pages/standards‐intro.html](https://www.gensc.org/pages/standards-intro.html)
1. Term search: <https://genomicsstandardsconsortium.github.io/mixs/term_list/>

## Data Management Tools

1. GBIF Metabarcoding Data Toolkit (MDT): <https://mdt.gbif.org/>
1. MDT User Guide: [https://docs.gbif‐uat.org/mdt‐user‐guide/en/](https://docs.gbif-uat.org/mdt-user-guide/en/)
1. GBIF‐US MDT: <https://mdt.gbif.us/> ; manager: Stephen Formel (sformel\@usgs.gov)
1. NOAA Omics Data Management Guide: [https://noaa‐omics‐dmg.readthedocs.io/en/latest/](https://noaa-omics-dmg.readthedocs.io/en/latest/)

## Community Pages

1. GBIF: <https://www.gbif.org/dna>
1. OBIS: [https://obis.org/2024/10/22/obis‐edna/](https://obis.org/2024/10/22/obis-edna/)

## References

- Creer, S., Deiner, K., Frey, S., Porazinska, D., Taberlet, P., Thomas, W.K., Potter, C., Bik, H.M., 2016. The ecologist’s field guide to sequence‐based identification of biodiversity. Methods in Ecology and Evolution 7, 1008–1018. [https://doi.org/10.1111/2041‐210X.12574](https://doi.org/10.1111/2041-210X.12574)

- eDNA Task Team of the Interagency Working Group on Biodiversity of the Subcommittee on Ocean Science and Technology Committee on Environment of the National Science & Technology Council. 2024. National Aquatic Environmental DNA Strategy. [https://www.whitehouse.gov/wpcontent/uploads/2024/06/NSTC_National‐Aquatic‐eDNA‐Strategy.pdf](https://www.whitehouse.gov/wp-content/uploads/2024/06/NSTC_National-Aquatic-eDNA-Strategy.pdf)

- Eloe‐Fadrosh, E.A., Mungall, C.J., Miller, M.A., Smith, M., Patil, S.S., Kelliher, J.M., Johnson, L.Y.D., Rodriguez, F.E., Chain, P.S.G., Hu, B., Thornton, M.B., McCue, L.A., McHardy, A.C., Harris, N.L., Reddy, T.B.K., Mukherjee, S., Hunter, C.I., Walls, R., Schriml, L.M., 2024. A Practical
Approach to Using the Genomic Standards Consortium MIxS Reporting Standard for Comparative Genomics and Metagenomics, in: Setubal, J.C.,
Stadler, P.F., Stoye, J. (Eds.), Comparative Genomics: Methods and Protocols. Springer US, New York, NY, pp. 587–609. [https://doi.org/10.1007/978‐1‐0716‐3838‐5_20](https://doi.org/10.1007/978-1-0716-3838-5_20)

- Finstad, A.G., Andersson, A., Bissett, A., Fossøy, F., Grosjean, M., Hope, M., Kõljalg, U., Lundin, D., Nilsson, H., Prager, M., Jeppesen, T.S., Svenningsen, C., Schigel, D., Abarenkov, K., Provoost, P., Suominen, S., Frøslev, T.G., 2023. Publishing DNA‐derived data through biodiversity data platforms. [https://doi.org/10.35035/DOC‐VF1A‐NR22](https://doi.org/10.35035/DOC-VF1A-NR22)

- Hirsch, S., Acharya‐Patel, N., Amamoo, P.A., Borrero‐Pérez, G.H., Cahyani, N.K.D., Ginigini, J.G.M., Hurley, K.K.C., Lopes‐Lima, M., Lopez, M.L., Mapholi, N., Ouattara, K.N., Pazmiño, D.A., Rii, Y., Thompson, F., Heyden, S. von der, Watsa, M., Yepes‐Narvaez, V., Allan, E.A., Kelly, R., 2024. Centering accessibility, increasing capacity, and fostering innovation in the development of international eDNA standards. Metabarcoding and Metagenomics 8, e126058. <https://doi.org/10.3897/mbmg.8.126058>

- Leigh, D.M., Vandergast, A.G., Hunter, M.E., Crandall, E.D., Funk, W.C., Garroway, C.J., Hoban, S., OylerMcCance, S.J., Rellstab, C., Segelbacher, G., Schmidt, C., Vázquez‐Domínguez, E., Paz‐Vinas, I., 2024. Best practices for genetic and genomic data archiving. Nat Ecol Evol 8, 1224–1232. [https://doi.org/10.1038/s41559‐024‐02423‐7](https://doi.org/10.1038/s41559-024-02423-7)

- Kirtane, A., Howard, L., Beaver, C.E., Hunter, M.E., Luikart, G., Deiner, K., 2024. How, What, and Where You Sample Environmental DNA Affects Diversity Estimates and Species Detection. Environmental DNA 6, e70042. <https://doi.org/10.1002/edn3.70042>

- Klymus, K.E., Baker, J.D., Abbott, C.L., Brown, R.J., Craine, J.M., Gold, Z., Hunter, M.E., Johnson, M.D., Jones, D.N., Jungbluth, M.J., Jungbluth, S.P., Lor, Y., Maloy, A.P., Merkes, C.M., Noble, R., Patin, N.V., Sepulveda, A.J., Spear, S.F., Steele, J.A., Takahashi, M., Watts, A.W., Theroux, S., 2024. The MIEM guidelines: Minimum information for reporting of environmental metabarcoding data. Metabarcoding and Metagenomics 8, e128689. <https://doi.org/10.3897/mbmg.8.128689>

- Rieder, J., Jemmi, E., Hunter, M.E., Adrian‐Kalchhauser, I., 2024. A Guide to Environmental DNA Extractions for Non‐Molecular Trained Biologists, Ecologists, and Conservation Scientists. Environmental DNA 6, e70002. <https://doi.org/10.1002/edn3.70002>

- Ruppert, K.M., Kline, R.J., Rahman, M.S., 2019. Past, present, and future perspectives of environmental DNA (eDNA) metabarcoding: A systematic review in methods, monitoring, and applications of global eDNA. Global Ecology and Conservation 17, e00547. <https://doi.org/10.1016/j.gecco.2019.e00547>

- Stein, E.D., Jerde, C.L., Allan, E.A., Sepulveda, A.J., Abbott, C.L., Baerwald, M.R., Darling, J., Goodwin, K.D., Meyer, R.S., Timmers, M.A., Thielen, P.M., 2024. Critical considerations for communicating environmental DNA science. Environmental DNA 6, e472. <https://doi.org/10.1002/edn3.472>
